# Generated by Django 4.1.3 on 2022-11-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounttype_useraccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='initial_deposit_date',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='initial_deposite_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
